// automatically generated by the FlatBuffers compiler, do not modify

package com.tus.binary.suite.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BidAskEntry extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BidAskEntry getRootAsBidAskEntry(ByteBuffer _bb) { return getRootAsBidAskEntry(_bb, new BidAskEntry()); }
  public static BidAskEntry getRootAsBidAskEntry(ByteBuffer _bb, BidAskEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BidAskEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long price() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long size() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int level() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte side() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte updateAction() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createBidAskEntry(FlatBufferBuilder builder,
      long price,
      long size,
      int level,
      byte side,
      byte updateAction) {
    builder.startTable(5);
    BidAskEntry.addSize(builder, size);
    BidAskEntry.addPrice(builder, price);
    BidAskEntry.addLevel(builder, level);
    BidAskEntry.addUpdateAction(builder, updateAction);
    BidAskEntry.addSide(builder, side);
    return BidAskEntry.endBidAskEntry(builder);
  }

  public static void startBidAskEntry(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addPrice(FlatBufferBuilder builder, long price) { builder.addLong(0, price, 0L); }
  public static void addSize(FlatBufferBuilder builder, long size) { builder.addLong(1, size, 0L); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(2, level, 0); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(3, side, 0); }
  public static void addUpdateAction(FlatBufferBuilder builder, byte updateAction) { builder.addByte(4, updateAction, 0); }
  public static int endBidAskEntry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BidAskEntry get(int j) { return get(new BidAskEntry(), j); }
    public BidAskEntry get(BidAskEntry obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

