// automatically generated by the FlatBuffers compiler, do not modify

package com.tus.binary.suite.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Instrument extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Instrument getRootAsInstrument(ByteBuffer _bb) { return getRootAsInstrument(_bb, new Instrument()); }
  public static Instrument getRootAsInstrument(ByteBuffer _bb, Instrument obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Instrument __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String symbol() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer symbolAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer symbolInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String exchange() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer exchangeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer exchangeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String currency() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer currencyAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer currencyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createInstrument(FlatBufferBuilder builder,
      int symbolOffset,
      int exchangeOffset,
      int currencyOffset) {
    builder.startTable(3);
    Instrument.addCurrency(builder, currencyOffset);
    Instrument.addExchange(builder, exchangeOffset);
    Instrument.addSymbol(builder, symbolOffset);
    return Instrument.endInstrument(builder);
  }

  public static void startInstrument(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSymbol(FlatBufferBuilder builder, int symbolOffset) { builder.addOffset(0, symbolOffset, 0); }
  public static void addExchange(FlatBufferBuilder builder, int exchangeOffset) { builder.addOffset(1, exchangeOffset, 0); }
  public static void addCurrency(FlatBufferBuilder builder, int currencyOffset) { builder.addOffset(2, currencyOffset, 0); }
  public static int endInstrument(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Instrument get(int j) { return get(new Instrument(), j); }
    public Instrument get(Instrument obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

