// automatically generated by the FlatBuffers compiler, do not modify

package com.tus.binary.suite.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MarketData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static MarketData getRootAsMarketData(ByteBuffer _bb) { return getRootAsMarketData(_bb, new MarketData()); }
  public static MarketData getRootAsMarketData(ByteBuffer _bb, MarketData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MarketData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String messageType() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageTypeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer messageTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long timestamp() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long sequenceId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int version() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public Instrument instrument() { return instrument(new Instrument()); }
  public Instrument instrument(Instrument obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public BidAskEntry bidAskEntries(int j) { return bidAskEntries(new BidAskEntry(), j); }
  public BidAskEntry bidAskEntries(BidAskEntry obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bidAskEntriesLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public BidAskEntry.Vector bidAskEntriesVector() { return bidAskEntriesVector(new BidAskEntry.Vector()); }
  public BidAskEntry.Vector bidAskEntriesVector(BidAskEntry.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMarketData(FlatBufferBuilder builder,
      int messageTypeOffset,
      long timestamp,
      long sequenceId,
      int version,
      int instrumentOffset,
      int bidAskEntriesOffset) {
    builder.startTable(6);
    MarketData.addSequenceId(builder, sequenceId);
    MarketData.addTimestamp(builder, timestamp);
    MarketData.addBidAskEntries(builder, bidAskEntriesOffset);
    MarketData.addInstrument(builder, instrumentOffset);
    MarketData.addVersion(builder, version);
    MarketData.addMessageType(builder, messageTypeOffset);
    return MarketData.endMarketData(builder);
  }

  public static void startMarketData(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addMessageType(FlatBufferBuilder builder, int messageTypeOffset) { builder.addOffset(0, messageTypeOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(1, timestamp, 0L); }
  public static void addSequenceId(FlatBufferBuilder builder, long sequenceId) { builder.addLong(2, sequenceId, 0L); }
  public static void addVersion(FlatBufferBuilder builder, int version) { builder.addInt(3, version, 0); }
  public static void addInstrument(FlatBufferBuilder builder, int instrumentOffset) { builder.addOffset(4, instrumentOffset, 0); }
  public static void addBidAskEntries(FlatBufferBuilder builder, int bidAskEntriesOffset) { builder.addOffset(5, bidAskEntriesOffset, 0); }
  public static int createBidAskEntriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBidAskEntriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMarketData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishMarketDataBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedMarketDataBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MarketData get(int j) { return get(new MarketData(), j); }
    public MarketData get(MarketData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

