// automatically generated by the FlatBuffers compiler, do not modify

package com.tus.binary.suite.fbs;

@SuppressWarnings("unused")
public final class Side {
  private Side() { }
  public static final byte BID = 0;
  public static final byte ASK = 1;

  public static final String[] names = { "BID", "ASK", };

  public static String name(int e) { return names[e]; }
}

