// automatically generated by the FlatBuffers compiler, do not modify

package com.tus.binary.suite.fbs;

@SuppressWarnings("unused")
public final class UpdateAction {
  private UpdateAction() { }
  public static final byte ADD = 0;
  public static final byte UPDATE = 1;
  public static final byte DELETE = 2;

  public static final String[] names = { "ADD", "UPDATE", "DELETE", };

  public static String name(int e) { return names[e]; }
}

